name: New Framework Test

on:
  pull_request:
    branches:
      - 'newtest_mac'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-TDengineNewFramework
  cancel-in-progress: true

jobs:
  test-new-cases:
    uses: taosdata/.github/.github/workflows/new-framework-test.yml@new-test-mac
    with:
      tdinternal: false
